### ISSUE TITLE
Behavior gets never called

### ISSUE THREAD

**Issue by KeKl** [wieslawsoltes/AvaloniaBehaviors#12]
Not sure if it is a avalonia or behavior Problem. I have following behavior:

    public class DoubleTappedBehavior : Behavior<TreeViewItem>
    {
        public static readonly AttachedProperty<ICommand> CommandProperty =
            AvaloniaProperty.RegisterAttached<DoubleTappedBehavior, TreeViewItem, ICommand>("Command", null, false, defaultBindingMode: Avalonia.Data.BindingMode.TwoWay);
        
        public static ICommand GetCommand(TreeViewItem element)
        {
            return element.GetValue(CommandProperty);
        }

        public static void SetCommand(TreeViewItem element, string value)
        {
            element.SetValue(CommandProperty, value);
        } 

        protected override void OnAttached()
        {
            base.OnAttached();
            AssociatedObject.DoubleTapped += DoubleTapped;
        }

        protected override void OnDetaching()
        {
            AssociatedObject.DoubleTapped -= DoubleTapped;
            base.OnDetaching();
        }

        private void DoubleTapped(object sender, RoutedEventArgs e)
        {
            if (Command == null)
                return;
            Command.Execute(null);
        }
    }

I use it this way:

   <TreeView Items="{Binding Items, ElementName=ToC, Mode=TwoWay}">

      <TreeView.Styles>
        <Style Selector="TreeViewItem">
          <Setter Property="commandBehaviors:DoubleTappedBehavior.Command"
                  Value="{Binding Command}"/>
        </Style>
      </TreeView.Styles>

    </TreeView>

The Get/Set Command is never get called. Also the attached method. Not sure where the problem is.

**Comment by wieslawsoltes** [comment]
What version are you using official NuGet or nightly build?

Try using nightly version of Avalonia:
https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

and nightly version of AvaloniaBehaviors.:
https://github.com/wieslawsoltes/AvaloniaBehaviors#nuget

**Comment by wieslawsoltes** [comment]
Currently you should use `Avalonia` version `0.5.2-build3857-alpha` and `AvaloniaBehaviors` version `0.5.2-build470-alpha`.

**Comment by KeKl** [comment]
ok.

**Comment by wieslawsoltes** [comment]
@KeKl Did you try Avalonia alpha build? Did it solve the issue?

**Comment by KeKl** [comment]
Not yet. Im still on 0.4.x

**Comment by wieslawsoltes** [comment]
@KeKl Please try version 0.6.0. Closing, please re-open if issue is present in 0.6.0.
