### ISSUE TITLE
Nightly build fails

### ISSUE THREAD

**Issue by mysteryx93** [wieslawsoltes/AvaloniaBehaviors#120]
Trying to run an app with the nightly build throws this error

    <PackageReference Include="Avalonia" Version="11.0.999-cibuild0030725-beta" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.0.999-build20230221-01" />

> System.TypeInitializationException: The type initializer for 'Avalonia.Xaml.Interactions.Core.EventTriggerBehavior' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.AvaloniaObject,!!1,!!1>)'.

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/8fba4b9fcf952f8a378c84bd80fbb0b893ec33a9/build/Avalonia.props#L4

**Comment by wieslawsoltes** [comment]
Use 11.0.999-cibuild0030320-beta

**Comment by mysteryx93** [comment]
Unfortunately, FluentAvalonia preview5.1 is targetting 30643-beta so that's not possible...

**Comment by mysteryx93** [comment]
Well I can still use FluentAvalonia-preview5

**Comment by wieslawsoltes** [comment]
Avalonia.Xaml.Behaviors.11.0.999-build20230226-01
