### ISSUE TITLE
Null value in expression

### ISSUE THREAD

**Issue by CreateLab** [wieslawsoltes/AvaloniaBehaviors#17]
try to bind like in your sample
``` xml
<ListBox x:Name="listBox" Grid.Row="3" Grid.Column="1" Items="{Binding Collection}"
                 SelectedItem="{Binding ShowObject}" >
            <i:Interaction.Behaviors>
                <ia:EventTriggerBehavior EventName="DoubleTapped" SourceObject="{Binding #listBox}">
                    <ia:InvokeCommandAction Command="{Binding EnterClickCommand}" />
                </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
            <ListBox.ItemTemplate>
                <DataTemplate>
                    <StackPanel Orientation="Horizontal">
                        <Image Source="{Binding Bitmap}" MaxHeight="25" MaxWidth="25" />
                        <TextBlock Text="{Binding Name}" />
                    </StackPanel>
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
```

but have an exception in debug output
`[Binding] Error in binding to "Avalonia.Xaml.Interactions.Core.InvokeCommandAction"."Command": "Null value in expression ''." (Avalonia.Xaml.Interactions.Core.InvokeCommandAction #63183526)`

use Avalonia 0.8.999
use behaviors 0.9.0

**Comment by wieslawsoltes** [comment]
@CreateLab Where is the `EnterClickCommand` defined?

**Comment by CreateLab** [comment]
@wieslawsoltes open agein and if u can contact with me in gitter 
in vm
 public ReactiveCommand<Unit,Unit> DownloadFileCommand { get; }
        public ReactiveCommand<Unit,Unit> EnterClickCommand { get; }
   EnterClickCommand = ReactiveCommand.Create(() => Console.Write("fsdfsd"));
