### ISSUE TITLE
ChangePropertyAction Is not performed 

### ISSUE THREAD

**Issue by honzasram** [wieslawsoltes/AvaloniaBehaviors#19]
Hi, 

I need some help with ChangePropertyAction. whenever I want to use it as in following example, its not working and I do not know why. I hope Somebody can steer me to right path.
Thanks
```XAML
<TextBlock Classes="DefaultStyle" Text="{Binding HouseBalanceInformation.Bilance, StringFormat=Bilance: {0}}" Name="HouseBilance">
    <i:Interaction.Behaviors>
        <ia:DataTriggerBehavior Binding="{Binding HouseBalanceInformation.Bilance}" ComparisonCondition="LessThan" Value="0">
            <ia:ChangePropertyAction TargetObject="{Binding $self}" PropertyName="Background" Value="#ff0000" />
        </ia:DataTriggerBehavior>
        <ia:DataTriggerBehavior Binding="{Binding HouseBalanceInformation.Bilance}" ComparisonCondition="GreaterThan" Value="0">
            <ia:ChangePropertyAction TargetObject="{Binding $self}" PropertyName="Background" Value="#00ff00" />
        </ia:DataTriggerBehavior>
    </i:Interaction.Behaviors>
</TextBlock>
```

**Comment by wieslawsoltes** [comment]
@honzasram 

Try this:
```XAML
<TextBlock x:Name="textBlock" Classes="DefaultStyle" Text="{Binding HouseBalanceInformation.Bilance, StringFormat=Bilance: {0}}" Name="HouseBilance">
    <i:Interaction.Behaviors>
        <ia:DataTriggerBehavior Binding="{Binding HouseBalanceInformation.Bilance}" ComparisonCondition="LessThan" Value="0">
            <ia:ChangePropertyAction TargetObject="{Binding #textBlock}" PropertyName="Background" Value="#ff0000" />
        </ia:DataTriggerBehavior>
        <ia:DataTriggerBehavior Binding="{Binding HouseBalanceInformation.Bilance}" ComparisonCondition="GreaterThan" Value="0">
            <ia:ChangePropertyAction TargetObject="{Binding #textBlock}" PropertyName="Background" Value="#00ff00" />
        </ia:DataTriggerBehavior>
    </i:Interaction.Behaviors>
</TextBlock>
```

**Comment by honzasram** [comment]
@wieslawsoltes Wow. Thank you for fast response.

Tied and still no coloring.
![image](https://user-images.githubusercontent.com/9151345/65072419-2a058180-d991-11e9-96ba-8bca15c2f2b2.png)

I noticed that if I set up color directly on TextBlock element i XAML, it will stay without background. That means, DataTrigger works but maybe do not understand Value part of ChangePropertyAction. Could be that the case? How to debug this sort of issues

**Comment by wieslawsoltes** [comment]
@honzasram You can try using sample app: https://github.com/wieslawsoltes/AvaloniaBehaviors/tree/master/samples/BehaviorsTestApplication

Here is some example:
https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/3d256fc1ce001cc608468c7561d3b8202343e1f1/samples/BehaviorsTestApplication/Controls/ChangePropertyActionControl.xaml#L10-L26
