### ISSUE TITLE
DataTriggerBehavior.ChangePropertyAction does not trigger on initial binding

### ISSUE THREAD

**Issue by stevozilik** [wieslawsoltes/AvaloniaBehaviors#26]
Seems like the ChangePropertyAction does not trigger on initial binding, only after the value changes.

Is there are away of controlling the behaviour? 

We are trying to replace DataTriggers from WPF and those run on initial binding as well

**Comment by wieslawsoltes** [comment]
https://github.com/microsoft/XamlBehaviorsWpf/pull/64
https://github.com/microsoft/XamlBehaviorsWpf/issues/11#issuecomment-564809638
