### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by Symbai** [wieslawsoltes/AvaloniaBehaviors#32]
I could only find samples for a single click. Is there a behavior that triggers on a double click?

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/b7be7ca642fd55244f7c1e9d328cdc0e14d39eea/src/Avalonia.Xaml.Interactions.Custom/ToggleIsExpandedOnDoubleTappedBehavior.cs#L14

It's in `Avalonia.Xaml.Interactions.Custom` nuget package.
