### ISSUE TITLE
IvalidOperation Exception when launching Sample App

### ISSUE THREAD

**Issue by Mrxx99** [wieslawsoltes/AvaloniaBehaviors#44]
When launching the sample app I get an IvalidOperationException in BehaviorsTestApplication.Controls.CallMethodActionControl on the TargteObject Binding of the first CallMethodAction. It says "AvaloniaValue.UnsetValue is not a valid value for BindingValue<>."

**Comment by wieslawsoltes** [comment]
@Mrxx99 Fixed on master branch.
