### ISSUE TITLE
Transformation of value in DataTriggerBehavior

### ISSUE THREAD

**Issue by MopsiMauser** [wieslawsoltes/AvaloniaBehaviors#48]
Hello everyone,

First of all I want to say thank you for this library!!! I have a question regarding DataTriggerBehavior: is it possible to use some transformation function on a binding value or have additional comparison conditions, for example in order to compare it case insensitive? example:

`<StackPanel>
    <i:Interaction.Behaviors>
      <ia:DataTriggerBehavior Binding="{Binding Person.LastName}" ComparisonCondition="Equal" Value="foo">
        <ia:ChangePropertyAction TargetObject="{Binding #LastName}" PropertyName="Foreground" Value="#FF0000" />
      </ia:DataTriggerBehavior>
    </i:Interaction.Behaviors>
    <TextBox Name="LastName" Classes="important" Text="{Binding Person.LastName}"></TextBox>
  </StackPanel>`

My goal is to compare Person.LastName case insensitive to foo.

**Comment by wieslawsoltes** [comment]
I think you can use value converters on bindings to have case insensitive comparison..

**Comment by wieslawsoltes** [comment]
http://avaloniaui.net/docs/binding/converting-binding-values
