### ISSUE TITLE
Apply Style in ChangePropertyAction

### ISSUE THREAD

**Issue by MopsiMauser** [wieslawsoltes/AvaloniaBehaviors#50]
Is it possible to apply/refer to a style in a ChangePropertyAction? I have this example XAML: 

```
<Window.Styles>
    <Style Selector="TextBox">
      <Setter Property="Margin" Value="0,10,0,0"></Setter>
      <Setter Property="Width" Value="100"></Setter>
      <Setter Property="Foreground" Value="#000000"></Setter>
    </Style>
    <Style Selector="Button:pointerover /template/ ContentPresenter">
      <Setter Property="CornerRadius" Value="20"></Setter>
    </Style>
  </Window.Styles>

  <StackPanel>
    <TextBox Text="{Binding Person.FirstName}"></TextBox>
    <TextBox Name="LastName" Text="{Binding Person.LastName}">
      <i:Interaction.Behaviors>
        <ia:DataTriggerBehavior Binding="{Binding Person.LastName, Converter={StaticResource toLowerStringConverter}}" ComparisonCondition="Equal" Value="schulz">
          <ia:ChangePropertyAction TargetObject="{Binding #LastName}" PropertyName="Foreground" Value="#FF0000" />
        </ia:DataTriggerBehavior>
        <ia:DataTriggerBehavior Binding="{Binding Person.LastName, Converter={StaticResource toLowerStringConverter}}" ComparisonCondition="NotEqual" Value="schulz">
          <ia:ChangePropertyAction TargetObject="{Binding #LastName}" PropertyName="Foreground" Value="#000000" />
        </ia:DataTriggerBehavior>
      </i:Interaction.Behaviors>
    </TextBox>
    <TextBox Text="{Binding Person.Age}"></TextBox>
    <Button Width="100" Margin="0,10,0,0" Command="{Binding IncrementAge}">Age++</Button>
  </StackPanel> 
```

If Peron.LastName has a specific value i want the foreground color to be red, else I want it to have the default color in my application, black in this case. But I also defined the foreground color in a style for all TextBoxes(<Style Selector="TextBox">....) . So I would like to be able to refer to/apply this style in the ChangePropertyAction to not have the foreground color defined at several locations in the file.

**Comment by wieslawsoltes** [comment]
You can probably set `Classes` property and use `<Style Selector="TextBox.yourclassname">

**Comment by MopsiMauser** [comment]
Unfortunately it does not work. I changed it to:

```
<Window.Styles>
    <Style Selector="TextBox">
      <Setter Property="Margin" Value="0,10,0,0"></Setter>
      <Setter Property="Width" Value="100"></Setter>
      <Setter Property="Foreground" Value="#000000"></Setter>
    </Style>
    <Style Selector="TextBox.important">
      <Setter Property="Foreground" Value="#FF0000"></Setter>
    </Style>
  </Window.Styles>

  <StackPanel>
    <TextBox Text="{Binding Person.FirstName}"></TextBox>
    <TextBox Name="LastName" Text="{Binding Person.LastName}">
      <i:Interaction.Behaviors>
        <ia:DataTriggerBehavior Binding="{Binding Person.LastName, Converter={StaticResource toLowerStringConverter}}" ComparisonCondition="Equal" Value="schulz">
          <ia:ChangePropertyAction TargetObject="{Binding #LastName}" PropertyName="Classes" Value="important" />
        </ia:DataTriggerBehavior>
        <ia:DataTriggerBehavior Binding="{Binding Person.LastName, Converter={StaticResource toLowerStringConverter}}" ComparisonCondition="NotEqual" Value="schulz">
          <ia:ChangePropertyAction TargetObject="{Binding #LastName}" PropertyName="Classes" Value="" />
        </ia:DataTriggerBehavior>
      </i:Interaction.Behaviors>
    </TextBox>
    <TextBox Text="{Binding Person.Age}"></TextBox>
    <Button Width="100" Margin="0,10,0,0" Command="{Binding IncrementAge}">Age++</Button>
  </StackPanel>
```

But the foreground color always stays black.

**Comment by MopsiMauser** [comment]
By the way, is this the proper way to check a property value and the opposite of it? Or does something like a "else" exist for a DataTriggerBehavior?

**Comment by wieslawsoltes** [comment]
Try using two classes maybe important and notimportant

**Comment by wieslawsoltes** [comment]
I think best is to use resources

https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/97e0149abfdbda4fd37a6f9fddcb89f960c08511/samples/BehaviorsTestApplication/Pages/DataTriggerBehaviorControl.xaml#L12

https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/97e0149abfdbda4fd37a6f9fddcb89f960c08511/samples/BehaviorsTestApplication/App.xaml#L15

**Comment by MopsiMauser** [comment]
I tried it with your suggested way using resources and the Fill property, but unfortunatlely it still doesn't work.

**Comment by MopsiMauser** [comment]
I noticed that I just copied your code without adjusting the property..... When I use the proper property Foreground it works!!! Thanks for your help. I just have another question: Is my way the right way to compare a value with an "if-else" case? Or is there a better way than using 2 DataTriggerBehaviors with Equal and NotEqual comparison conditions respectively ?

**Comment by wieslawsoltes** [comment]
> I noticed that I just copied your code without adjusting the property..... When I use the proper property Foreground it works!!! Thanks for your help. 

Great to hear!

> I just have another question: Is my way the right way to compare a value with an "if-else" case? Or is there a better way than using 2 DataTriggerBehaviors with Equal and NotEqual comparison conditions respectively ?

Not aware on better way, you can try google how in WPF/UWP they do, XAML should be the same.

**Comment by wieslawsoltes** [comment]
@MopsiMauser 
https://gist.github.com/maxkatz6/2c765560767f20cf0483be8fac29ff22
https://github.com/AvaloniaUI/Avalonia/issues/2427#issuecomment-689240642
