### ISSUE TITLE
Avalonia.Xaml.Behaviors returns an error when installed Avalonia packages>=0.10.999-cibuild0011414

### ISSUE THREAD

**Issue by PopMal** [wieslawsoltes/AvaloniaBehaviors#54]
Error CS0012 the "AvaloniaObject" type is defined in an Assembly that is not referenced. You should add a link to " Avalonia.Base versions=0.10.0.0, cultures=neutral, PublicKeyToken values=null"

`using Avalonia.Controls;`
`using Avalonia.Xaml.Interactivity;`
`public class ButtonBehaviers : Behavior<TextBox>
    {
    }`

Since these packages are preliminary and there are stable versions of Avalonia and Behaviors, I just wanted you to know about this conflict in advance.

**Comment by wieslawsoltes** [comment]
Probably some breaking change in Avalonia or something else got broken.

**Comment by wieslawsoltes** [comment]
Please try 0.10.0-preview6, latest Avalonia nightly builds are not tested very often.
