### ISSUE TITLE
It should be possible to use "x:Null" in CommandParameter

### ISSUE THREAD

**Issue by maxkatz6** [wieslawsoltes/AvaloniaBehaviors#58]
https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/master/src/Avalonia.Xaml.Interactions/Core/InvokeCommandAction.cs#L109

**Comment by wieslawsoltes** [comment]
@maxkatz6 Will fix

**Comment by wieslawsoltes** [comment]
Original had https://github.com/microsoft/XamlBehaviors/blob/c7273bd95e85a054d912c765075f4bb9a8d89ab1/src/BehaviorsSDKManaged/Microsoft.Xaml.Interactions/Core/InvokeCommandAction.cs#L161
