### ISSUE TITLE
Unable to resolve

### ISSUE THREAD

**Issue by nlogozzo** [wieslawsoltes/AvaloniaBehaviors#60]
Hi, 
I'm getting the error "Unable to resolve type Interaction from namespace using:Avalonia.Xaml.Interactivity Line 1, position 2".
I installed the package `Avalonia.Xaml.Behaviors` V0.10.0 and this is my code below in my MainWindowView.axaml file:

```xaml
<Window x:Class="NickvisionMoney.Views.MainWindowView"
		xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
		xmlns:i="using:Avalonia.Xaml.Interactivity"
        xmlns:ia="using:Avalonia.Xaml.Interactions.Core"
        mc:Ignorable="d" Name="Window" Title="{Binding Title}" Icon="/Assets/icon.ico"
        Width="800" Height="600" FontFamily="Segoe UI" WindowState="Maximized">
```
```xaml
	<i:Interaction.Behaviors>
		<ia:EventTriggerBehavior EventName="Closing" SourceObject="{Binding ElementName=Window}">
			<ia:InvokeCommandAction Command="{Binding ExitCommand}"/>
		</ia:EventTriggerBehavior>
	</i:Interaction.Behaviors>
```

If i try to build the program with this file open I get this error and my designer claims invalid markup. However, if i close this file in visual studio and build the project then I get no errors and the program runs successfully. I wouldn't mind doing this, but the annoyance is the designer not working and having to close this file every time before building and running. Any ideas what's going on?

**Comment by nlogozzo** [comment]
With the help of a friend, changing it to
```
xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions"
```
Fixed the issue

**Comment by yansigit** [comment]
I was just able to fix the same issue with same solution.
Sample codes should be replaced with codes above, instead of codes with `using` which is not working.
