### ISSUE TITLE
Combobox : EventTriggerBehavior SelectionChanged is triggered before the SelectedItem

### ISSUE THREAD

**Issue by Whiletru3** [wieslawsoltes/AvaloniaBehaviors#89]
Hello,

In a mvvm combobox, the EventTriggerBehavior SelectionChanged is triggered before the SelectedItem

```
<ComboBox x:Name="cmbMainLang"
      assists:ComboBoxAssist.Label="{Binding Hint}"
      PlaceholderText="{Binding Hint}"
      MaxDropDownHeight="200"
      Margin="0 40 0 0"
      DataContext="{Binding UILanguagesComboBox}"
      Items="{Binding Items}"
      SelectedItem="{Binding Selected}">
    <Interaction.Behaviors>
        <EventTriggerBehavior EventName="SelectionChanged">
          <InvokeCommandAction Command="{Binding SelectCommand}"/>
        </EventTriggerBehavior>
    </Interaction.Behaviors>
</ComboBox>
```

This lead to an unsynchonized combobox value & command

Thanks

**Comment by Whiletru3** [comment]
is there any workaround for this issue ?

**Comment by wieslawsoltes** [comment]
You can observe Selected property from view model and execute action or method.

**Comment by Whiletru3** [comment]
@wieslawsoltes : Hello, we found a workaround using ValueChangedTriggerBehavior.

```
<ComboBox x:Name="cmbMainLang"
                              assists:ComboBoxAssist.Label="{Binding Hint}"
                              PlaceholderText="{Binding Hint}"
                              MaxDropDownHeight="200"
                              Margin="0 40 0 0"
                              DataContext="{Binding UILanguagesComboBox}"
                              Items="{Binding Items}"
                              SelectedItem="{Binding Selected}">
  <Interaction.Behaviors>
	<ValueChangedTriggerBehavior Binding="{Binding Selected}">
               <InvokeCommandAction Command="{Binding SelectCommand}"/>
         </ValueChangedTriggerBehavior>
    </Interaction.Behaviors>
</ComboBox>
```

Do you agree that it is a good workaround ?

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes : Hello, we found a workaround using ValueChangedTriggerBehavior.
> 
> ```
> <ComboBox x:Name="cmbMainLang"
>                               assists:ComboBoxAssist.Label="{Binding Hint}"
>                               PlaceholderText="{Binding Hint}"
>                               MaxDropDownHeight="200"
>                               Margin="0 40 0 0"
>                               DataContext="{Binding UILanguagesComboBox}"
>                               Items="{Binding Items}"
>                               SelectedItem="{Binding Selected}">
>   <Interaction.Behaviors>
> 	<ValueChangedTriggerBehavior Binding="{Binding Selected}">
>                <InvokeCommandAction Command="{Binding SelectCommand}"/>
>          </ValueChangedTriggerBehavior>
>     </Interaction.Behaviors>
> </ComboBox>
> ```
> 
> Do you agree that it is a good workaround ?

I would not call it workaround, more like correct solution to what Avalonia framework currently does.

**Comment by Whiletru3** [comment]
Of course :) thanks a lot for the confirmation
